version: '3.4'

services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
  # http://localhost:7000/pedido/api/values
  # http://localhost:7000/catalogo/api/values

  pedido:
    image: pedido
    build:
      context: .
      dockerfile: Pedido/Dockerfile
  # http://localhost:6001/api/values

  catalogo:
    image: catalogo
    build:
      context: .
      dockerfile: Produto/Dockerfile
  # http://localhost:6002/api/values